version: '3'


includes:
  dnsmasq:
    dir: setting-up-dnsmasq
    taskfile: ./setting-up-dnsmasq/Taskfile.yaml
    aliases:
      - dns


tasks:
  default:
    desc: Show help
    cmds:
      - task --list
      - |
        echo -e "\033[1;32m==============================\033[0m"
        echo -e "\033[1;33mHelp Menu\033[0m"
        echo -e "\033[1;32m==============================\033[0m"
        echo -e "\033[1;34m- To set up dnsmasq for Fedora 41:\033[0m"
        echo -e "  \033[1;36mtask dns:up\033[0m"
        echo ""
        echo -e "\033[1;34m- To set up the Kind cluster and test load balancer functionality:\033[0m"
        echo -e "  \033[1;36mtask all\033[0m"
        echo ""
        echo -e "\033[1;34m- To then view the Nginx site in your browser:\033[0m"
        echo -e "  Navigate to \033[1;36mhttp://nginx.local-env.test\033[0m"
        echo ""
        echo -e "\033[1;34m- To undo dnsmasq configuration for Fedora 41:\033[0m"
        echo -e "  \033[1;36mtask dns:down\033[0m"
        echo ""
        echo -e "\033[1;34m- To delete the Kind cluster:\033[0m"
        echo -e "  \033[1;36mtask clean\033[0m"
        echo -e "\033[1;32m==============================\033[0m"

  setup-cluster:
    desc: Create a Kind cluster with MetalLB configuration
    cmds:
      - chmod +x kind-cluster-with-metallb.sh
      - ./kind-cluster-with-metallb.sh
    silent: false

  test-loadbalancer:
    desc: Test load balancer functionality
    cmds:
      - chmod +x test-loadbalancer-functionality.sh
      - ./test-loadbalancer-functionality.sh
    silent: false

  all:
    desc: Run both setup-cluster and test-loadbalancer tasks
    cmds:
      - task: setup-cluster
      - task: test-loadbalancer

  clean:
    desc: Delete the Kind cluster
    cmds:
      - kind delete cluster
    silent: false
